# Generated by Django 5.1.5 on 2025-02-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_name_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
